name: pheasant_temp
description: >-
  The Pheasant Framework Templating Engine to Create Renderable Dart Code for Pheasant Code.
version: 0.1.0-alpha
repository: https://github.com/pheasantframework/pheasant_temp

environment:
  sdk: '>=3.0.0'

# Add regular dependencies here.
dependencies:
  analyzer: ^6.3.0
  code_builder: ^4.9.0
  dart_style: ^2.3.4
  html: ^0.15.4
  markdown: ^7.1.1
  pheasant_meta: ^0.1.0-alpha
  pheasant_assets: ^0.1.0-alpha

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  

dependency_overrides: 
  pheasant_meta:
    path: ../pheasant_meta
  pheasant_assets:
    path: ../pheasant_assets

topics:
  - pheasant
  - pheasant_temp
  - web