name: raven_temp
description: The Raven Framework Templating Engine to Create Renderable Dart Code for Raven Code.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0'

# Add regular dependencies here.
dependencies:
  analyzer: ^6.3.0
  code_builder: ^4.9.0
  dart_style: ^2.3.4
  html: ^0.15.4
  meta: ^1.11.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
